version: "3.7"

services:
  frontend:
    image: shopping-website-client
    container_name: shopping-website-client
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4200:80"
volumes:
  db-data:
